spring.application.name=arq_m3_s3_eda_intro_lms

# Soporte para RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Retry
spring.rabbitmq.listener.simple.retry.enabled = true
spring.rabbitmq.listener.simple.retry.max-attempts = 3
spring.rabbitmq.listener.simple.retry.initial-interval = 1000
spring.rabbitmq.listener.simple.retry.multiplier = 2

# DLQ
spring.rabbitmq.listener.simple.default-requeue-rejected=false

